services:
  nextjs-app:
    image: chl11wq12/kosta-2-nextjs-app:v1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app
    ports:
      - "$FRONTEND_PORT:${FRONTEND_PORT}"
    env_file: .env
    environment:
      - NODE_ENV=production
      - FRONTEND_PORT=${FRONTEND_PORT}
      - BACKEND_URL=${BACKEND_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped
